QUESTION 2 : Module 2 segment 1 ou 3 je pense et on peut surement faire une approximation en série de taylor pcq la discrétisation d'ordre 2 coincide avec l'approximation de Taylor d'ordre 2 mais la même chose pour des opérateurs ?
https://en.wikipedia.org/wiki/Finite_difference_coefficient

In [18]:
import numpy
import sympy
from matplotlib import pyplot
%matplotlib inline

Question 1 analytiquement je te la laisse j'ai pris une photo de la résolution de eliott si tu veux

## Question 2 

Nous avons pour commencer la variable discrétisée $\xi$,
$$\xi_m=m\Delta$$
où $m=0,...,100$.

On a alors $c_m=c(\xi_m,t)$ et $w_m=w(\xi_m,t)$.

En utilisant les différences finies d'ordre 2, on peut réecrire les opérateurs suivants sous forme matricielle, 
$$L_{i,j}=\big( \frac{R_a}{4t}\frac{\partial^2}{\partial \xi^2}-k^2\big)_{i,j}$$
$$M_{i,j}=\frac{1}{t}\big( \frac{1}{4}\frac{\partial^2}{\partial \xi^2}+\frac{\xi}{2}\frac{\partial}{\partial \xi}-\frac{k^2t}{R_a})_{i,j}$$

Commençons avec $L_{i,j}$ : 

Posons la fonction $u_m=c_m$ où $u_m=w_m$. En appliquant l'opérateur sur $u_m$, il est possible d'exprimer les dérivées en différences finies. Comme nous évaluerons le dérivées d'ordre 2 dans ce travail, nous trouvons comme différence centrale finie : 
$$\frac{\partial^2 u}{\partial \xi^2}=\frac{u_{i+1}-2u{i}+u_{i-1}}{\Delta^2}$$

(coéficient donner dans https://en.wikipedia.org/wiki/Finite_difference_coefficient)

De même, pour la "Forward and backward finite difference", nous avons :
$$\frac{\partial^2 u}{\partial \xi^2}=\frac{2u_{i}-5u_{i+1}+4u_{i+2}-u_{i+3}}{\Delta^2}$$
$$\frac{\partial^2 u}{\partial \xi^2}=\frac{2u_{i}-5u_{i-1}+4u_{i-2}-u_{i-3}}{\Delta^2}$$

Ceux-ci sont nécessaire pour établir les coéfficients de nos matrices aux bords (en $\xi=0$ et $\xi=\infty$). Revenons à notre opérateurs. Nous voyons ensuite que nous multiplions cette dérivées secondes par un certains paramètre et qu'ensuite nous soustrayons par un autre paramètre. On a de ce fait l'expression suivante (pour i entre 1 et 99) :
$$L_{i,j}=\frac{R_a}{4t}\frac{u_{i+1}-2u_{i}+u_{i-1}}{\Delta^2}-k^2u_i$$

On remarque que pour chaque $i$, on a 3 coeficients. A partir de ceci on peut construire une matrice pour le premier terme de $L_{i,j}$, et le deuxième terme est alors simplement le terme $k^2$ multiplier par l'identité. On aura alors : --> Matrice a mieux faire !!!
$$L_{i,j}= \frac{R_a}{4t\Delta^2}
\quad
\begin{pmatrix} 
. \\
 & .\\
 & & .\\
 &... & 0& 1 & -2 & 1 & 0 & ... \\
 & &... & 0& 1 & -2 & 1 & 0 & ... \\
 & & & & & & & .\\
 & & & & & & & & .
\end{pmatrix}
\quad
\begin{pmatrix}
u_0\\
u_1\\
.\\
.\\
\end{pmatrix}
-k^2I
\begin{pmatrix}
u_0\\
u_1\\
.\\
.\\
\end{pmatrix}$$

Il reste à déterminer les coéficients de la première ligne et la dernière, pour ceci nous utiliserons les conditions aux bords donné dans l'énoncé. La méthode des différences finies centrale ne peut fonctionner dans le cas échéant étant donné que nous ne pouvons pas prendre l'élément précédant i.e. $u_{i-1}$. Donc nous utiliserons la méthode de forward finite difference. 

On a en $u_0$,
$$\frac{\partial^2 u}{\partial \xi^2}=\frac{2u_{0}-5u_{1}+4u_{2}-u_{3}}{\Delta^2}$$

et en $u_{100}$,
$$\frac{\partial^2 u}{\partial \xi^2}=\frac{2u_{100}-5u_{99}+4u_{98}-u_{97}}{\Delta^2}$$

La matrice devient alors,
$$L_{i,j}= \frac{R_a}{4t\Delta^2}
\quad
\begin{pmatrix} 
2 & -5 & 4 & -1 & 0 & ...\\
0 & 1 & -2 & 1 & 0 & ...\\
 & & .\\
 & & & .\\
 & & & & .\\ 
 ... & 0 & 1 & -2 & 1 & 0 \\
  & ... & -1 & 4 & -5 & 2
\end{pmatrix}
\quad
\begin{pmatrix}
u_0\\
u_1\\
.\\
.\\
\end{pmatrix}
-k^2I
\begin{pmatrix}
u_0\\
u_1\\
.\\
.\\
\end{pmatrix}$$

Mais, nous savons que en $\xi=0$ et $\xi=\infty$, la valeur de $u$ est nulle, on peut les supprimer étant donné qu'ils n'interviennent plus dans la suite, (mieux formuler)

La matrice devient alors,
$$L_{i,j}= \frac{R_a}{4t\Delta^2}
\quad
\begin{pmatrix} 
 -5 & 4 & -1 & 0 & ...\\
 1 & -2 & 1 & 0 & ...\\
 & & .\\
 & & & .\\
 & & & & .\\ 
 ... & 0 & 1 & -2 & 1 \\
  & ... & -1 & 4 & -5
\end{pmatrix}
\quad
\begin{pmatrix}
u_1\\
u_2\\
.\\
.\\
u_{99}
\end{pmatrix}
-k^2I
\begin{pmatrix}
u_1\\
u_2\\
.\\
.\\
u_{99}
\end{pmatrix}$$

FAIRE LA MEME CHOSE POUR M

In [47]:
#Construction des matrices + voir si c'est mieux d'enlever les ifs
def matrix(N):  #trouver boucle for en une ligne dans mooc
    mat = numpy.zeros((N-2,N-2))
    for i in range(0,N-2):
        if i==0:
            mat[i][0]=-5
            mat[i][1]=4
            mat[i][2]=-1
        elif i==N-3:
            mat[i][N-3]=-5
            mat[i][N-4]=4
            mat[i][N-5]=-1
        else :
            mat[i][i]=-2
            mat[i][i-1]=1
            mat[i][i+1]=1
    print(mat)
matrix(11)

[[-5.  4. -1.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  0. -1.  4. -5.]]


## Question 3

Nous allons vérifier que la fonction $f(\xi)=e^{-\xi^2}h(\xi)$ est bien fonction propre de l'opérateur
$$Hf=\frac{1}{4}\frac{\partial^2 f}{\partial \xi^2}+\frac{\xi}{2}\frac{\partial f}{\partial \xi}=\alpha f$$

Pour ce faire, on a l'information que $h$ est solution de l'équation de Hermite $h''-2\xi h'=-2\lambda h$.

Remplaçons $f$ et résolvons :
\begin{align*}
Hf &= \frac{1}{4}\frac{\partial^2 \big(e^{-\xi^2}h(\xi)\big)}{\partial \xi^2}+\frac{\xi}{2}\frac{\partial \big(e^{-\xi^2}h(\xi)\big)}{\partial \xi^2}\\
   &= \frac{1}{4} \frac{\partial}{\partial \xi}\Big[(-2\xi) e^{-\xi^2}h(\xi) + e^{-\xi^2}h'(\xi)\Big] + \frac{\xi}{4}\Big[-4\xi e^{-\xi^2}h(\xi)+2e^{-\xi^2}h'(\xi)\Big]\\
   &= \frac{1}{4}\Big[-2e^{-\xi^2}h(\xi)+4\xi^2e^{-\xi^2}h(\xi)-2\xi e^{-\xi^2}h'(\xi) -2\xi e^{-\xi^2}h'(\xi)+e^{-\xi^2}h''(\xi)\Big]+\frac{\xi}{4}\Big[-4\xi e^{-\xi^2}h(\xi)+2e^{-\xi^2}h'(\xi)\Big]\\
   &=\frac{e^{-\xi^2}}{4}\Big[h''(\xi)-2\xi h'(\xi)-2h(\xi)\Big]\\
   &=-\frac{e^{-\xi^2}}{2}(\lambda+1)h(\xi)\\
   &=-\frac{(\lambda+1)}{2}f(\xi)\\
   &=\alpha f(\xi)\\
\end{align*}

On remarque que $f$ est bien fonction propre de l'opérateur, et $\alpha=\frac{-(\lambda+1)}{2}$. 

Maintenant, nous allons utiliser les valeurs aux bords pour trouver les valeurs admissibles de $\alpha$. A FAIRE